ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPSUPERFK
    FOREIGN KEY (Super_ssn) REFERENCES EMPLOYEE (Ssn);

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPDNOFK
    FOREIGN KEY (Dno) REFERENCES DEPARTMENT (Dnumber);
